variable "PROJECT_NAME" {}
variable "VPC_CIDR" {}
variable "PUB_SUB_1_A_CIDR" {}
variable "PUB_SUB_2_B_CIDR" {}
variable "PRI_SUB_3_A_CIDR" {}
variable "PRI_SUB_4_B_CIDR" {}
variable "PRI_SUB_5_A_CIDR" {}
variable "PRI_SUB_6_B_CIDR" {}
variable "CLIENT_PUB_KEY" {}
variable "INSTANCE_TYPE" {}
variable "env_prefix" {}
variable "ami_id" {}
variable "pri_sub_3_a" {}
variable "pri_sub_4_b" {}
variable "subnet_ids"   {}
variable "source_security_group" {}
variable "rds_password" {}
variable "vpc_id" {}